### ISSUE TITLE
请教如何使用

### ISSUE THREAD

**Issue by qizhenyu** [youqingkui/ninghao_reptile#1]
您好，很喜欢您的工具，但因为实在是新手，所以有两个问题想要请教：
1. 我登陆后获取了 session 键值，和您提供的截图一样，我看到了 SESSeb（省略一长串） 和 又一长串字符。我不知道怎样组装成组装成类似:'SESSeb=yoNFPAN', 即 some=someting 的字符，可以说详细一点吗？
2. “修改 ninghao 结束两个参数获取到得cookie” 请问具体应该修改哪一行代码呢？修改成什么样呢？

非常感谢！

**Comment by youqingkui** [comment]
![image](https://cloud.githubusercontent.com/assets/7046903/7019722/985e253a-dd45-11e4-854d-2b5972a20262.png)
看到有个Name，还有个Value，把值拼接成Name=Value, 及中间价格`=`号。
假设Name为`SESSeb41eba184e0681dc06c845e44`, Value为`NdCuV68GXv-6zhG-FneGjeoNZhYT5QpI5`, 则拼接的字符串为：
'SESSeb41eba184e0681dc06c845e44=NdCuV68GXv-6zhG-FneGjeoNZhYT5QpI5'

替换掉app.js 166行, 将loginCookie复制为拼接的字符串。
然后downUrlArr 赋值你需要下载的课程地址数组。
保存代码，然后 `node app` 运行程序。

适当使用，避免加重ninghao的服务器的负担。

**Comment by qizhenyu** [comment]
非常感谢！一定会注意当使用。

另外，运行后看到出现一个 undefined 的提示。如图：https://cldup.com/PkSC1aewp2.png

请问这样是正常的吗？

**Comment by youqingkui** [comment]
看截图，应该是这行代码的输出，可以忽略。
console.log(process.env.NingHao)

**Comment by qizhenyu** [comment]
好的，多谢！
