### ISSUE TITLE
无法下载了

### ISSUE THREAD

**Issue by qizhenyu** [youqingkui/ninghao_reptile#2]
这两天准备下载课程时，出现「无法找到课程列表」的提示，不知道是否可以更新一下，让它可以正常工作呢？

![无法找到课程列表](https://cldup.com/r4st39U3JA.jpg)

非常感谢！

**Comment by qizhenyu** [comment]
@youqingkui 可以帮忙看一下吗？很感谢！

**Comment by youqingkui** [comment]
抱歉，这个代码没有更新了。因为ninghao.net改版了，所以不能用了。
